from pydantic import BaseModel, Field
from typing import Optional

# ==========================================
# PHASE 1: TRIAGE SCHEMAS
# ==========================================
class TriageRequest(BaseModel):
    symptoms_text: str = Field(..., description="Raw text description of symptoms typed by the user.")
    spo2: Optional[float] = Field(None, description="Peripheral capillary oxygen saturation level percentage.")
    heart_rate: Optional[float] = Field(None, description="Heart rate measured in beats per minute (BPM).")
    blood_pressure_sys: Optional[float] = Field(None, description="Systolic blood pressure (top number).")
    blood_pressure_dia: Optional[float] = Field(None, description="Diastolic blood pressure (bottom number).")

class TriageResponse(BaseModel):
    is_emergency_bypass: bool = Field(..., description="Flag indicating if deterministic vital limits were breached.")
    extracted_symptoms: list[str] = Field(..., description="Clean clinical symptom tags parsed by the engine.")
    plain_language_rationale: str = Field(..., description="User-friendly medical explanation of the current condition assessment.")
    red_flags: list[str] = Field(..., description="High-risk symptoms or critical warnings highlighted for prominent UI display.")


# ==========================================
# PHASE 2: CHRONIC SCHEMAS (Make sure these are here!)
# ==========================================
class MetricTrendRequest(BaseModel):
    condition_name: str = Field(..., description="Name of the tracked chronic condition (e.g., Type 2 Diabetes).")
    metric_history: list[float] = Field(..., description="Array of historical numeric readings logged by the user.")

class MetricTrendResponse(BaseModel):
    is_adverse_trend: bool = Field(..., description="Flag indicating if dangerous variance or steady climbing was detected.")
    nudge_text: str = Field(..., description="Empathetic, contextual text warning or behavioral nudge for the UI.")

class ReportGenerationRequest(BaseModel):
    patient_name: str = Field("Anonymous Patient", description="Masked or consented name of the individual.")
    condition_name: str = Field(..., description="Tracked chronic condition.")
    weekly_metrics: list[float] = Field(..., description="Last 7 numeric logs to draw on the visual overview grid.")
    summary_text: str = Field(..., description="A short clinical summary paragraph detailing recent observations.")

class HistoryProcessRequest(BaseModel):
    user_token: str = Field(..., description="Unique anonymized token representing the client device instance.")
    raw_ocr_text: str = Field(..., description="Unfiltered raw text extracted natively via Google ML Kit on-device.")

class HistoryProcessResponse(BaseModel):
    user_token: str
    is_sanitized: bool
    scrubbed_clinical_text: str = Field(..., description="Clean clinical timeline string completely devoid of personal identities.")

class ProbableConditionItem(BaseModel):
    condition_name: str = Field(..., description="Name of probable condition (e.g., Migraine with Aura).")
    severity_remark: str = Field(..., description="Severity level: 'HIGH', 'MEDIUM', or 'LOW'.")
    description: str = Field(..., description="Brief clinical explanation linking symptoms to condition.")

class PredictedCondition(BaseModel):
    condition_name: str = Field(..., description="Standardized clinical name of the condition.")
    probability_score: float = Field(..., description="Probability likelihood score between 0.0 and 1.0 generated by the LLM.")
    base_severity_score: float = Field(..., description="Systemic baseline impact multiplier extracted from local dataset matrix.")
    calculated_risk_index: float = Field(..., description="Compounded situational priority metric.")

class TriageResponse(BaseModel):
    is_emergency_bypass: bool = Field(..., description="Flag indicating if deterministic vital limits were breached.")
    extracted_symptoms: list[str] = Field(..., description="Clean clinical symptom tags parsed by the engine.")
    probable_conditions: list[ProbableConditionItem] = Field(default=[], description="3 to 4 probable conditions with severity remarks (HIGH, MEDIUM, LOW).")
    triage_reasoning: str = Field("", description="Reasoning explaining why top condition was given priority.")
    clinical_explanation: str = Field("", description="Explanation of condition and recommended medications.")
    recommended_next_steps: list[str] = Field(default=[], description="Actionable next steps for treatment and recovery.")
    critical_red_flags: list[str] = Field(default=[], description="Critical warning symptoms that signal a red alert if they occur.")
    predicted_diagnoses: list[PredictedCondition] = Field(default=[], description="Array of matching conditions backed by probability and severity values.")
    plain_language_rationale: str = Field("", description="User-friendly explanation of the assessment matching these records.")
    red_flags: list[str] = Field(default=[], description="High-risk symptoms or critical warnings highlighted for UI display.")


class TriageRequest(BaseModel):
    symptoms_text: str = Field(..., description="Raw text description of symptoms typed by the user.")
    patient_id: Optional[str] = Field(None, description="Patient ID linked to query.")
    include_medical_history: bool = Field(True, description="User toggle switch to include/exclude medical history context.")
    scrubbed_history_context: Optional[str] = Field(None, description="Privacy-anonymized historical clinical timeline context from Phase 3.")
    chat_history: Optional[list[dict]] = Field(default=[], description="Recent conversation history turns (context window).")
    spo2: Optional[float] = Field(None, description="Peripheral capillary oxygen saturation level percentage.")
    heart_rate: Optional[float] = Field(None, description="Heart rate measured in beats per minute (BPM).")
    blood_pressure_sys: Optional[float] = Field(None, description="Systolic blood pressure (top number).")
    blood_pressure_dia: Optional[float] = Field(None, description="Diastolic blood pressure (bottom number).")


class MedicalFileSanitizeResponse(BaseModel):
    user_token: str
    file_name: str
    extracted_text_preview: str = Field(..., description="First 200 characters of raw extracted text.")
    scrubbed_clinical_text: str = Field(..., description="Clean clinical data completely stripped of PII/PHI.")
    detected_indicators: list[str] = Field(..., description="List of standardized disease matrix tokens recognized in the document.")


# ==========================================
# PATIENT REGISTRATION SCHEMAS
# ==========================================
class PatientRegistrationRequest(BaseModel):
    phone_number: str = Field(..., description="Verified phone number of the patient.")
    first_name: str = Field(..., description="First name of the patient.")
    last_name: str = Field(..., description="Surname/Last name of the patient.")
    email: Optional[str] = Field(None, description="Optional email address.")
    age: int = Field(..., description="Age of the patient.")
    gender: str = Field(..., description="Gender identity of the patient.")
    blood_group: str = Field(..., description="Blood group designation (e.g., A+, O-).")
    chronic_diseases: Optional[list[str]] = Field(default=[], description="List of chronic health conditions.")
    consent_given: bool = Field(..., description="Consent status for Terms & Conditions.")
    permissions_granted: list[str] = Field(default=[], description="List of granted system permissions.")

class PatientProfileResponse(BaseModel):
    patient_id: str = Field(..., description="Unique generated patient ID (e.g. HT-2026-X89K-L).")
    status: str = Field("success", description="Status of database operation.")
    message: str = Field(..., description="Confirmation message.")
    data: dict = Field(..., description="Stored patient profile object.")

class PatientUpdateRequest(BaseModel):
    phone_number: Optional[str] = Field(None, description="Updated phone number.")
    first_name: Optional[str] = Field(None, description="Updated first name.")
    last_name: Optional[str] = Field(None, description="Updated surname.")
    email: Optional[str] = Field(None, description="Updated email address.")
    age: Optional[int] = Field(None, description="Updated age.")
    gender: Optional[str] = Field(None, description="Updated gender.")
    blood_group: Optional[str] = Field(None, description="Updated blood group.")
    chronic_diseases: Optional[list[str]] = Field(None, description="Updated list of chronic conditions.")
    consent_given: Optional[bool] = Field(None, description="Updated consent status.")
    permissions_granted: Optional[list[str]] = Field(None, description="Updated granted system permissions.")


# ==========================================
# MEDICAL REPORT ANALYSIS SCHEMAS
# ==========================================
class LabVitalItem(BaseModel):
    metric: str = Field(..., description="Name of lab metric (e.g., Fasting Blood Sugar, HbA1c, SpO2).")
    value: str = Field(..., description="Recorded numerical value.")
    unit: str = Field(..., description="Measurement unit (e.g., mg/dL, %, bpm).")
    status: str = Field(..., description="Status (Normal, High, Low, Critical).")

class ReportAnalysisResponse(BaseModel):
    patient_id: str = Field(..., description="Unique Patient ID linked to document.")
    file_name: str = Field(..., description="Original name of uploaded medical report file.")
    report_type: str = Field(..., description="Categorized type (e.g., Complete Blood Count, Radiology, Prescription).")
    report_date: str = Field(..., description="Date of document/test.")
    redaction_summary: dict = Field(..., description="Local security scrubber redaction stats.")
    key_findings: list[str] = Field(..., description="Clinical observation bullet points.")
    lab_vitals: list[LabVitalItem] = Field(default=[], description="Structured lab vitals metrics parsed by Gemini.")
    clinical_summary: str = Field(..., description="Empathetic, clear patient-facing summary.")



    